name: chat_frontend_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart:
  flutter_bloc: 
  bloc:
  provider:
  http:
  flutter_socket_io:
  web_socket_channel:
  socket_io_client:
  socket_io_common:

dev_dependencies:
  flutter_test:
    sdk: flutter  

flutter:
  uses-material-design: true

module:
  androidX: true